name: bli
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Map and location
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  
  # HTTP requests
  dio: ^5.4.0
  
  # Freezed for immutable models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # State management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  mockito: ^5.4.6
  build_runner: ^2.4.16
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#128C7E"
  adaptive_icon_foreground: "assets/app_icon.png"
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  macos:
    generate: true
    image_path: "assets/app_icon.png"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  linux:
    generate: true
    image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#009688"
  image: assets/app_icon.png
  android: true
  ios: true
  web: true
  android_12:
    color: "#009688"
    image: assets/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/

